### ISSUE TITLE
updates to GeoJSON representation

### ISSUE THREAD

**Issue by tomkralidis** [World-Meteorological-Organization/bufr2geojson#2]
Sample output below.  Items to consider:

- change temperature units from Kelvin to Celsius
- can we make each `observation` property name the CF name/long name (i.e. `#1#airTemperature` -> `air_temperature`)?
- as well, should we also consider whether it is possible to flatten the GeoJSON? So:
```
"properties": {
    "air_temperature.°C": 15.55,
    "dew_point_temperature.°C": 13.65,
    ...
}
```
The strong typing provides broad interop (imagine CSV download of the properties).

```json
    {
      "id": "WIGOS_0-454-2-AWSNAMITAMBO_20210707T145500",
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          35.27,
          -15.84,
          806
        ]
      },
      "properties": {
        "identifier": "WIGOS_0-454-2-AWSNAMITAMBO_20210707T145500",
        "phenomenonTime": "2021-07-07T14:55:00+00:00",
        "resultTime": "2022-02-15T16:54:03+00:00",
        "wmo:wigos_station_identifier": "0-454-2-AWSNAMITAMBO",
        "observations": {
          "#1#nonCoordinatePressure": {
            "value": 93284.05,
            "cf_standard_name": "air_pressure",
            "units": "Pa",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": 807,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#pressureReducedToMeanSeaLevel": {
            "value": 102745.5,
            "cf_standard_name": "pressure_at_mean_sea_level",
            "units": "Pa",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": 807,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#3HourPressureChange": {
            "value": null,
            "longname": "change_of_air_pressure_over_past_3_hours",
            "units": "Pa",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": 807,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#characteristicOfPressureTendency": {
            "value": 4,
            "longname": "characteristic_of_pressure_tendency",
            "units": "CODE TABLE",
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#airTemperature": {
            "value": 288.7,
            "cf_standard_name": "air_temperature",
            "units": "K",
            "sensor_height_above_local_ground": 1.5,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#dewpointTemperature": {
            "value": 286.8,
            "cf_standard_name": "dew_point_temperature",
            "units": "K",
            "sensor_height_above_local_ground": 1.5,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#relativeHumidity": {
            "value": 88,
            "cf_standard_name": "relative_humidity",
            "units": "%",
            "sensor_height_above_local_ground": 1.5,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#totalSunshine": {
            "value": 0,
            "cf_standard_name": "duration_of_sunshine",
            "units": "min",
            "time_period": "-1 h",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#2#totalSunshine": {
            "value": 0,
            "cf_standard_name": "duration_of_sunshine",
            "units": "min",
            "time_period": "-24 h",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#totalPrecipitationOrTotalWaterEquivalent": {
            "value": 0,
            "cf_standard_name": "precipitation_amount",
            "units": "kg m-2",
            "time_period": "-1 h",
            "sensor_height_above_local_ground": 1.5,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#maximumTemperatureAtHeightAndOverPeriodSpecified": {
            "value": 289.5,
            "cf_standard_name": "air_temperature",
            "cell_methods": "maximum",
            "units": "K",
            "time_period1": "-24 h",
            "time_period2": "0 h",
            "sensor_height_above_local_ground": 1.5,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#minimumTemperatureAtHeightAndOverPeriodSpecified": {
            "value": 269.4,
            "cf_standard_name": "air_temperature",
            "cell_methods": "minimum",
            "units": "K",
            "time_period1": "-24 h",
            "time_period2": "0 h",
            "sensor_height_above_local_ground": 1.5,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#windDirection": {
            "value": 188,
            "cf_standard_name": "wind_from_direction",
            "units": "deg",
            "cell_methods": 2,
            "time_period": "-10 min",
            "sensor_height_above_local_ground": 2,
            "sensor_height_above_mean_sea_level": null,
            "wind_sensor_type": 0,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#windSpeed": {
            "value": 2.975,
            "cf_standard_name": "wind_speed",
            "units": "m/s",
            "cell_methods": 2,
            "time_period": "-10 min",
            "sensor_height_above_local_ground": 2,
            "sensor_height_above_mean_sea_level": null,
            "wind_sensor_type": 0,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#maximumWindGustSpeed": {
            "value": 7.16,
            "cf_standard_name": "wind_speed",
            "units": "m/s",
            "cell_methods": null,
            "time_period": null,
            "sensor_height_above_local_ground": 2,
            "sensor_height_above_mean_sea_level": null,
            "wind_sensor_type": 0,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#1#globalSolarRadiationIntegratedOverPeriodSpecified": {
            "value": 0.02758914,
            "cf_standard_name": "surface_downwelling_shortwave_flux_in_air",
            "units": "J m-2",
            "cell_methods": "sum",
            "time_period": "-1 h",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          },
          "#2#globalSolarRadiationIntegratedOverPeriodSpecified": {
            "value": 0.02758914,
            "cf_standard_name": "surface_downwelling_shortwave_flux_in_air",
            "units": "J m-2",
            "cell_methods": "sum",
            "time_period": "-24 h",
            "sensor_height_above_local_ground": null,
            "sensor_height_above_mean_sea_level": null,
            "valid_min": null,
            "valid_max": null,
            "scale": null,
            "offset": null
          }
        },
        "id": "WIGOS_0-454-2-AWSNAMITAMBO_20210707T145500"
      }
    },
```

**Comment by tomkralidis** [comment]
cc @webb-ben

(@david-i-berry can you re-open this issue?  Looks like I am unable to)

As discussed with @david-i-berry today:
- granularity for OM GeoJSON output is one Feature per observed property
- enables wider array of data types
- easier transformation of BUFR data without apriori knowledge

```yaml
$schema: https://json-schema.org/draft/2020-12/schema
$id: https://raw.githubusercontent.com/wmo-im/wcmp2/main/schema/link.yaml
title: WMO GeoJSON profile for observations and measurements
description: WMO GeoJSON profile for observations and measurements

allOf:
  - $ref: https://raw.githubusercontent.com/opengeospatial/ogcapi-features/master/core/openapi/schemas/featureGeoJSON.yaml
properties:
  allOf:
    - $ref: https://raw.githubusercontent.com/opengeospatial/ogcapi-common/master/core/openapi/schemas/confClasses.yaml
  conformsTo:
    $ref: 
    "https://raw.githubusercontent.com/opengeospatial/ogcapi-common/master/core/openapi/schemas/confClasses.yaml#/properties/conformsTo"
    const: 
  properties:
    type: object
    properties:
      phenomenonTime:
        type: string
        format: date
        description: TODO
      resultTime:
        type: string
        format: date
        description: TODO
      name:
        type: string
        description: TODO
      description:
        type: string
        description: TODO
      units:
        type: string
        description: TODO
      value:
        type: number
        description: TODO
      metadata:
        type: object
        description: TODO
    required:
      - phenomemonTime
      - name
      - value
```

Suggested next steps:
- implement and test in bufr2geojson and wis2box
  - update as required
- document schema
- produce 3/4 instance examples
- provide a 1/2 pager/presentation for next OGC OM SWG
